name: Instagram Bot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_bot:
    runs-on: ubuntu-latest
    
    steps:
      # الخطوة 1: تنزيل الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v3

      # الخطوة 2: إعداد بيئة Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # تحديد إصدار بايثون المناسب

      # الخطوة 3: تثبيت المكتبات المطلوبة
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # تثبيت جميع المكتبات في requirements.txt

      # الخطوة 4: تشغيل السكربت
      - name: Run insta bot
        run: |
          python insta_bot.py  # تشغيل السكربت بعد تثبيت المكتبات
