# 4. (الجديدة) حذف ملفات الكاش القديمة
    - name: Clean Instabot Cache
      run: rm -rf *.json 
      
    # 5. تشغيل كود البوت
    - name: Run Instagram Bot Script
      env:
        # ... (متغيرات البيئة) ...
      run: python insta_bot.py
